name: secure_social_messaging_app
description: A new Flutter project for Secure Social Messaging.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.0.0
  flutter_riverpod: ^2.4.0
  google_fonts: ^6.1.0
  lucide_icons: ^0.1.0
  cupertino_icons: ^1.0.6
  camera: ^0.10.5+5
  flutter_animate: ^4.3.0
  qr_flutter: ^4.1.0
  pinput: ^3.0.1
  shared_preferences: ^2.2.2
  flutter_slidable: ^3.0.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  web_socket_channel: ^2.4.0
  sodium_libs: ^2.0.0
  web3dart: ^2.7.0
  bip39: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
